### ISSUE TITLE
Why is the repository not showing proper results?

### ISSUE THREAD

**Issue by JafferWilson** [shrestha-bikash/major_project#1]
Hello,
I have ran your repository and is working fine.  
The only concern I have is related to the output of  the 5 Personality Traits.   
Can you tell me why I am getting the output as 1 all the time? See the image:    
![screenshot](https://user-images.githubusercontent.com/13446197/30630700-84f8e016-9d96-11e7-9f5b-06e662275d17.png)

**Comment by JafferWilson** [comment]
Can you help me with this please?

**Comment by shrestha-bikash** [comment]
Is there any word in the words cloud shown below, if not then there may api error while fetching data from facebook. You should allow permission to get status during login with facebook and also you should configure your facebook app according to that.

**Comment by JafferWilson** [comment]
Yes, I got your point. I forgot to give the permissions, I guess.
