### ISSUE TITLE
Which Facebook API you have used here? Please let me know about it. 

### ISSUE THREAD

**Issue by JafferWilson** [shrestha-bikash/major_project#2]
The application is unable to fetch the data because of the unavailability of the response from the API.
Kindly, mention the API of Facebook used in this application so that I can verify.

**Comment by shrestha-bikash** [comment]
Sorry for the late comment, I was away for sometime. Facebook Graph Api was used here to fetch the data.

**Comment by JafferWilson** [comment]
Thank you for your reply.... :)
